USE ROLE ACCOUNTADMIN;
DROP USER IF EXISTS SVC_DEPLOY;
--------------------------------
-- DROP ROLES
--------------------------------
DROP ROLE IF EXISTS DEPLOY_ROLE;
DROP ROLE IF EXISTS ADM_CONTROL_ALERTS_FULL_AR;
DROP ROLE IF EXISTS ADM_CONTROL_ALERTS_R_AR;
DROP ROLE IF EXISTS ADM_CONTROL_ALERTS_RW_AR;
DROP ROLE IF EXISTS ADM_CONTROL_DB_WH_WO_AR;
DROP ROLE IF EXISTS ADM_CONTROL_DB_WH_WU_AR;
DROP ROLE IF EXISTS ADM_CONTROL_DEPLOY_FULL_AR;
DROP ROLE IF EXISTS ADM_CONTROL_DEPLOY_R_AR;
DROP ROLE IF EXISTS ADM_CONTROL_DEPLOY_RW_AR;
DROP ROLE IF EXISTS ADM_CONTROL_SYSADMIN_FR;
DROP ROLE IF EXISTS ADM_CONTROL_TAGS_FULL_AR;
DROP ROLE IF EXISTS ADM_CONTROL_TAGS_R_AR;
DROP ROLE IF EXISTS ADM_CONTROL_TAGS_RW_AR;
DROP ROLE IF EXISTS ADM_WH_WO_AR;
DROP ROLE IF EXISTS ADM_WH_WU_AR;
DROP ROLE IF EXISTS CPG_ANALYST_FR;
DROP ROLE IF EXISTS CPG_ENGINEER_FR;
DROP ROLE IF EXISTS CPG_SYSADMIN_FR;
DROP ROLE IF EXISTS DNA_ANALYST_FR;
DROP ROLE IF EXISTS DNA_ENGINEER_FR;
DROP ROLE IF EXISTS DNA_SYSADMIN_FR;
DROP ROLE IF EXISTS FIN_CUSTOMER_CUST360_FULL_AR;
DROP ROLE IF EXISTS FIN_CUSTOMER_CUST360_R_AR;
DROP ROLE IF EXISTS FIN_CUSTOMER_CUST360_RW_AR;
DROP ROLE IF EXISTS FIN_CUSTOMER_DB_WH_WO_AR;
DROP ROLE IF EXISTS FIN_CUSTOMER_DB_WH_WU_AR;
DROP ROLE IF EXISTS FIN_CUSTOMER_SYSADMIN_FR;
DROP ROLE IF EXISTS MGT_SYSADMIN_FR;
DROP ROLE IF EXISTS PDE_SYSADMIN_FR;
DROP ROLE IF EXISTS PDE_TAGADMIN_FR;

--------------------------------
-- DROP GIT INTEGRATIONS
--------------------------------
USE SCHEMA ADM_CONTROL_DB.DEPLOY;
-- USE SCHEMA MGT_CONTROL_DB.DEPLOY_SCHEMA;
DROP SECRET IF EXISTS GITHUB_SECRET;
DROP INTEGRATION IF EXISTS GITHUB_API_INTEGRATION;
DROP GIT REPOSITORY IF EXISTS SNOWFLAKE_GIT_REPO;
--------------------------------
-- DROP DBS
--------------------------------
DROP DATABASE IF EXISTS DEV_DB;
DROP DATABASE IF EXISTS ADM_CONTROL_DB;
DROP DATABASE IF EXISTS PRD_DB;
DROP DATABASE IF EXISTS QA_DB;
DROP DATABASE IF EXISTS FIN_CUSTOMER_DB;
DROP DATABASE IF EXISTS MGT_CONTROL_DB;
DROP DATABASE IF EXISTS TAXI_TEST;
DROP DATABASE IF EXISTS NYC_TAXI;
DROP DATABASE IF EXISTS DEMO_DB;
--------------------------------
-- DROP WAREHOUSES
--------------------------------
DROP WAREHOUSE IF EXISTS ADM_CONTROL_DB_WH;
DROP WAREHOUSE IF EXISTS FIN_CUSTOMER_DB_WH;
DROP WAREHOUSE IF EXISTS MGT_CONTROL_DB_WH;
DROP WAREHOUSE IF EXISTS DEPLOYMENT_WH;
DROP ROLE IF EXISTS SVC_DEPLOY;
